### ISSUE TITLE
Can't load app in db:environment if a config/database.yml file exists

### ISSUE THREAD

**Issue by lsimoneau** [jhollinger/grape-activerecord#7]
Our project uses ENVied to refer to database host, username, etc. in the `config/database.yml` file, so we need to have loaded ENVied before loading active_record and connecting to the database. This project's README suggests putting such application loading in a rake task `db:environment`. This would load fine if our database config was located somewhere else, but since it's in `config/database.yml` your `defaults.rb` file calls `database_file=` _before_ this environment task is executed, which fails because ENVied hasn't loaded yet.

It would be preferable if grape-activerecord didn't set the database file until the end of the database environment task, so that if any setup is required in order for activerecord to use the database file it can be performed there.

**Comment by jhollinger** [comment]
So you have a `database.yml` file, but it references some `ENV` variables that haven't been set yet? Just making sure I understand.

**Comment by dnagir** [comment]
@jhollinger that's the problem I have as well. `database.yml` refers to the environment vars using other gems which isn't loaded when `grape-activerecord` is required.

It looks like the issue is that `grape-activerecord` establishes the connection when the library is just required which is a bit eager to do.

It would be good if there was separate call required to establish connection so that we could be specific when we want to do it.

**Comment by jhollinger** [comment]
If you need a workaround right now, you could rename/move your `database.yml`, then call `Grape::ActiveRecord.database_file = "config/db.yml"` after initializing your `ENV`.

I was hoping to provide 0-configuration for the common case of having a `config/database.yml` file, while allowing uncommon cases to specify their own config. But I get where you're coming from - maybe explicit is better. So everyone would have to call [one of these methods](https://github.com/jhollinger/grape-activerecord#advanced-options) manually I guess? A breaking change, but an easy one I suppose. I'm open to other ideas if you have them.

**Comment by jhollinger** [comment]
I cut a new git tag with some changes that make db config/init explicit. You can try it in your `Gemfile` with:

    gem 'grape-activerecord', git: 'https://github.com/jhollinger/grape-activerecord.git', tag: 'v2.0.0-rc1'

An updated README is at https://github.com/jhollinger/grape-activerecord/tree/v2.0.0-rc1#2-configure-your-database-connection. Seems to work fine in some of my apps. Let me know how it goes and I'll cut a proper 2.0.0 release on rubygems.

**Comment by dnagir** [comment]
Thanks @jhollinger. That looks good :+1: 

Just a minor suggestion while still on a breaking change :smile: 
It would be a lot better if you'd provide specific methods for configuration rather than assignments.

When I use the assignment (`Grape::ActiveRecord.database_file = "config/database.yml"`) I presume it only set the file name and doesn't do much.

This would be a lot more explicit and intention revealing: `Grape::ActiveRecord.configure_from_file!("config/database.yml")`

**Comment by jhollinger** [comment]
Yeah I can see your point. Not crazy about the verbosity. But if I can't think of anything shorter soon I'll probably just go with your suggesion. Thanks.

**Comment by jhollinger** [comment]
Just pushed 2.0.0 out to Rubygems. Thanks.

**Comment by dnagir** [comment]
Thank you, much appreciated :+1:
